### ISSUE TITLE
Release of resources

### ISSUE THREAD

**Issue by dhruv2601** [chenxu05037/COSPLAY#1]
Dear authors,

Loved your approach in the COSPLAY paper! Is there a plan to release the resources sometime soon? Looking forward to trying the models.

**Comment by Guaguago** [comment]
Hi, thank you for the reply, we plan to release the code at this Thursday (11.24) then you can try it out.

**Comment by chenxu05037** [comment]
Hi, thank you very much for the reply! we plan to release the code at this Thursday (11.24) then you can try it out.

**Comment by dhruv2601** [comment]
Thank you Chen for sharing the resources, I will start exploring the code.
Closing the issue now.

**Comment by chenxu05037** [comment]
OK we have successful test the code. you can try it and contact me if any
problem met.

Dhruv rathi ***@***.***> 于2022年11月25日周五 12:43写道：

**Comment by chenxu05037** [comment]
[image: 截屏2022-11-26 下午11.18.05.png]

Chen Xu ***@***.***> 于2022年11月26日周六 23:17写道：
